# Generated by Django 5.1.4 on 2024-12-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caldo_cana', '0002_alter_cliente_email_alter_pedido_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
