# Generated by Django 5.1.4 on 2024-12-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caldo_cana', '0003_pedido_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
